name: Example Workflow
on: push

jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello this is a first run"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Goodbye"
