name: 01 - Building Blocks
on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: "say-hello"
        run: echo "Hello, World!"


  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          exit 1
          echo "Exited with code 1 "

      - name: Say goodbye
        run: echo "Goodbye!"


